local ls = require 'luasnip'
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s('frac', {
    t '\\dfrac{',
    i(1, 'num'),
    t '}{',
    i(2, 'denom'),
    t '}',
  }),

  s('mcq', {
    t {
      '\\mc',
      '',
    },
    i(1, 'QUESTION'),
    t {
      '',
      '\\begin{choices}',
      '  \\choice ',
    },
    i(2, 'Choice 1'),
    t {
      '',
      '  \\choice ',
    },
    i(3, 'Choice 2'),
    t {
      '',
      '  \\choice ',
    },
    i(4, 'Choice 3'),
    t {
      '',
      '  \\choice ',
    },
    i(5, 'Choice 4'),
    t {
      '',
      '\\end{choices}',
    },
  }),

  s('qp', {
    t {
      '\\documentclass[addpoints,12pt]{exam}',
      '% ==========================',
      '% FONTS & MATH',
      '% ==========================',
      '\\usepackage{newtxtext}',
      '\\usepackage{newtxmath}',
      '\\usepackage{mathtools}',
      '% ==========================',
      '% PAGE LAYOUT',
      '% ==========================',
      '\\usepackage[margin=1in]{geometry}',
      '\\usepackage{multicol}',
      '\\usepackage{array}',
      '\\usepackage{multirow}',
      '\\usepackage{booktabs}',
      '\\usepackage{enumerate}',
      '% ==========================',
      '% COLORS & SCREEN',
      '% ==========================',
      '\\usepackage{xcolor}',
      '\\usepackage[color]{tiscreen}',
      '\\definecolor{tiscreenbg}{HTML}{ffffff}',
      '\\definecolor{tiscreenfg}{HTML}{000000}',
      '% ==========================',
      '% GRAPHICS & FLOATS',
      '% ==========================',
      '\\usepackage{graphicx}',
      '\\usepackage{caption}',
      '\\usepackage{capt-of}',
      '\\usepackage{siunitx}',
      '% ==========================',
      '% TIKZ & PGFPLOTS',
      '% ==========================',
      '\\usepackage{tikz}',
      '\\usepackage{tkz-euclide}',
      '\\usepackage{scalerel}',
      '\\usepackage{pict2e}',
      '\\usetikzlibrary{calc,patterns,arrows.meta,shadows,external}',
      '\\usepackage{pgfplots}',
      '\\pgfplotsset{compat=newest}',
      '\\usepgfplotslibrary{statistics,fillbetween}',
      '% ==========================',
      '% CUSTOM INFO',
      '% ==========================',
      '\\newcommand{\\class}{\\textbf{',
    },
    i(1, 'class'),
    t {
      '}}',
      '\\newcommand{\\examnum}{\\textbf{',
    },
    i(2, 'exam number'),
    t {
      '}}',
      '\\newcommand{\\examdate}{',
    },
    i(3, 'date'),
    t {
      '}',
      '\\newcommand{\\name}{\\hfill \\textbf{Name}: \\underline{\\hspace{3in}}}',
      '\\newcommand{\\acl}{\\text{m}/\\text{s}^2}',
      '\\newcommand{\\dg}{^\\circ}',
      '\\newcommand{\\scin}[2]{$#1 \times 10^{#2}$}',
      '\\frenchspacing',
      '\\def\\tiscreenX{16}',
      '\\def\\tiscreenY{8}',
      '\\newcommand{\\mc}{\\question[2]}',
      '\\newcommand{\\tf}[1][{}]{\\question[2]%',
      '\\fillin[#1][0.25in]%',
      '}',
      '\\newcommand{\\shorta}{\\question[4]}',
      '%%%%%%%%%%',
      '% Uncomment whichever choice you make, use \\solution for each problem if you want given solutions',
      '%%%%%%%%%%',
      '% \\printanswers',
      '% \\noprintanswers',
      '\\extrawidth{0.5in}',
      '\\bracketedpoints',
      '\\pointsinrightmargin',
      '\\frenchspacing',
    },
    t {
      '',
      '\\begin{document}',
      '',
      '\\setlength\\fillinlinelength{1in}',
      '\\setlength\\answerclearance{0.2ex}',
      '\\correctchoiceemphasis{\\color{red}\\bfseries}',
      '\\renewcommand{\\solutiontitle}{\\noindent\\textbf{Solution:}\\par\\noindent}',
      '',
      '% This is where you change the header of the first page and the running header',
      '\\pagestyle{headandfoot}',
      '\\ifprintanswers',
      '  \\firstpageheader{\\Large{{\\class}}}{\\Large{\\examnum}}{\\Large \\textbf{ANSWER KEY}}',
      '  \\runningheader{\\class\\ - \\textbf{ANSWERS}}{Page \\thepage\\ of \\numpages}{\\examdate}',
      '  \\runningheadrule',
      '\\else',
      '  \\firstpageheader{\\Large{{\\class}}}{\\Large{\\examnum}}{\\examdate}',
      '  \\runningheader{\\class\\ - \\examnum}{Page \\thepage\\ of \\numpages}{\\examdate}',
      '  \\runningheadrule',
      '\\fi',
      '',
      '% \\runningheader{\\class\\ - \\examnum}{Page \\thepage\\ of \\numpages}{\\examdate}',
      '% \\runningheadrule',
      '% \\runningfooter{Page \\thepage\\ of \\numpages}{}{}',
      '',
      '\\name',
      '',
      '\\vspace{0.5em}',
      '',
      '\\noindent{\\rule{\\textwidth}{0.4pt}}',
      '',
      '\\begin{questions}',
      '',
    },
    i(0),
    t { '', '\\end{questions}', '\\end{document}' },
  }),

  s('hdr', {
    t {
      '\\pagestyle{headandfoot}',
      '\\ifprintanswers',
      '  \\firstpageheader{\\Large{{\\class}}}{\\Large{\\examnum}}{\\Large \\textbf{ANSWER KEY}}',
      '  \\runningheader{\\class\\ - \\textbf{ANSWERS}}{Page \\thepage\\ of \\numpages}{\\examdate}',
      '  \\runningheadrule',
      '\\else',
      '  \\firstpageheader{\\Large{{\\class}}}{\\Large{\\examnum}}{\\Large \\textbf{\\examdate}}',
      '  \\runningheader{\\class\\ - \\examnum}{Page \\thepage\\ of \\numpages}{\\examdate}',
      '  \\runningheadrule',
      '\\fi',
    },
  }),

  s('que', {
    t '\\question[',
    i(1, 'pts'),
    t { ']', '' },
    i(2, 'question'),
    t { '', '\\vfill', '' },
  }),
}
